# Generated by Django 5.0.6 on 2024-06-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecords',
            old_name='patient',
            new_name='patientId',
        ),
    ]
