# Generated by Django 5.0.3 on 2024-06-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patientrecords_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecords',
            name='respRate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
