# Generated by Django 5.0.3 on 2024-06-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_patientrecords_resprate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
