# Generated by Django 5.0.3 on 2024-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_room_patient_bed_rename_location_patient_ward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description available.')),
                ('treatment', models.TextField(default='No treatment information available.')),
                ('diagnosis', models.TextField(default='No diagnosis information available.')),
                ('symptoms', models.TextField(default='No symptoms information available.')),
            ],
        ),
    ]
