# Generated by Django 5.0.3 on 2024-07-01 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_patientdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patientdescription',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientdescription',
            name='patientId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='description', serialize=False, to='api.patient'),
        ),
        migrations.AlterField(
            model_name='patientrecords',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.patient'),
        ),
    ]
