import React from "react";
import img from "./../assets/logo.png"; // Importing logo image from assets folder

const Footer = () => {
  return (
    <footer className="bg-gray-800 font-roboto text-gray-300 py-4">
      {" "}
      {/* Footer section with background color, font style, and padding */}
      <div className="mx-auto px-4 md:px-8 flex flex-col md:flex-row items-center justify-between">
        {" "}
        {/* Container for flex layout, adjusting padding for different screen sizes */}
        {/* Left section containing logo and text information */}
        <div className="flex flex-col md:flex-row items-center gap-2">
          <img src={img} alt="logo" className="w-auto h-8 border-1 rounded" />{" "}
          {/* Logo image displayed with specified width, height, border, and rounded corners */}
          <div className="flex flex-col gap-2 md:gap-5">
            <span className="text-xl font-bold">Charak Centre IIT Indore</span>{" "}
            {/* Title with bold font */}
            <span className="text-sm">
              ©2024 Charak Centre IIT Indore. All rights reserved
            </span>{" "}
            {/* Copyright notice */}
            <div className="flex flex-col md:flex-row gap-2">
              <span className="font-bold text-slate-400">Disclaimer:</span>{" "}
              {/* Disclaimer label with bold font */}
              <span className="text-slate-500">
                This software is under development. Please consult with a doctor
                before acting on any decisions/interface generated by this tool.
              </span>{" "}
              {/* Disclaimer text */}
            </div>
          </div>
        </div>
        {/* Right section containing navigation links */}
        <div className="flex flex-col md:flex-row space-y-2 md:space-y-0 space-x-0 md:space-x-5 mt-4 md:mt-0">
          <a
            href="https://charakcenter.iiti.ac.in"
            className="hover:text-white text-sm"
          >
            About
          </a>{" "}
          {/* Link to About page */}
          <a href="#" className="hover:text-white text-sm">
            Contact
          </a>{" "}
          {/* Link to Contact page */}
          <a href="#" className="hover:text-white text-sm">
            Privacy Policy
          </a>{" "}
          {/* Link to Privacy Policy page */}
          <a href="#" className="hover:text-white text-sm">
            Terms of Service
          </a>{" "}
          {/* Link to Terms of Service page */}
        </div>
      </div>
    </footer>
  );
};

export default Footer;
